[tool.poetry]
name = "tfrlrl"
version = "0.0.0"
description = "Yet another Python RL library"
authors = ["Thomas Furmston <tfurmston@googlemail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tfurmston/tfrlrl"

[tool.poetry.build]
generate-setup-file = false

[tool.poetry.dependencies]
python = "~3.10"
ray = "^2.0.0"
numpy = "^2.0.0"
gymnasium = {version = "^1.1.0", extras = ["atari", "accept-rom-license", "mujoco"] }
dynaconf = "^3.1.12"
lightning = "^2.6.1"

[tool.poetry.group.dev.dependencies]
bumpversion = "^0.6.0"
ruff = "^0.14"
pytest = "^8.2"
pytest-cov = "^6.2"
pytest-mock = "^3.15"
pytest-random-order = "^1.0.4"
pytest-sugar = "^0.9"
tox = "^3.18"
hypothesis = "^6.36.1"
pre-commit = "^3.2.0"
mypy = "^1.20.0"

[tool.poetry.scripts]
tfrlrl-sample = "tfrlrl.cli.sample:main"
tfrlrl-sgd = "tfrlrl.cli.sgd:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length=120
multi_line_output=3
include_trailing_comma=true

[tool.pytest.ini_options]
markers = [
    "flaky: marks tests as flaky (deselect with '-m \"not flaky\"')",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
exclude = [".git", ".venv"]
select = ["B", "D", "E", "F", "G", "I", "LOG", "Q"]
ignore = ["D100", "D104", "D203", "D212", "Q000", "Q003"]

[tool.ruff.format]
quote-style = "single"
